# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_OJRnTuDowK9h71ZRmte13DqvQVPmeCP
"""

import loader_datasets
import net_model
import train_net

trainloader, testloader = loader_datasets.load_dataset()[0], loader_datasets.load_dataset()[2]

net = net_model.get_net()

train_net.train(trainloader, net)